CREATE TABLE language (
    id SERIAL CONSTRAINT DEF_PK_LANGUAGE PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE book_language (
    book_id INTEGER NOT NULL,
    language_id INTEGER NOT NULL,
    CONSTRAINT DOUBLE_PK_BOOK_LANGUAGE PRIMARY KEY(book_id, language_id)
);

ALTER TABLE book_language ADD CONSTRAINT DEF_FK_BOOK_BOOK_LANGUAGE FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE RESTRICT;

ALTER TABLE book_language ADD CONSTRAINT DEF_FK_LANGUAGE_BOOK_LANGUAGE FOREIGN KEY (language_id) REFERENCES language (id) ON DELETE RESTRICT;